// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dal-go/dalgo/ddl (interfaces: Applier)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_ddl/applier.go github.com/dal-go/dalgo/ddl Applier
//

// Package mock_ddl is a generated GoMock package.
package mock_ddl

import (
	context "context"
	reflect "reflect"

	dal "github.com/dal-go/dalgo/dal"
	dbschema "github.com/dal-go/dalgo/dbschema"
	ddl "github.com/dal-go/dalgo/ddl"
	gomock "go.uber.org/mock/gomock"
)

// MockApplier is a mock of Applier interface.
type MockApplier struct {
	ctrl     *gomock.Controller
	recorder *MockApplierMockRecorder
	isgomock struct{}
}

// MockApplierMockRecorder is the mock recorder for MockApplier.
type MockApplierMockRecorder struct {
	mock *MockApplier
}

// NewMockApplier creates a new mock instance.
func NewMockApplier(ctrl *gomock.Controller) *MockApplier {
	mock := &MockApplier{ctrl: ctrl}
	mock.recorder = &MockApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplier) EXPECT() *MockApplierMockRecorder {
	return m.recorder
}

// ApplyAddField mocks base method.
func (m *MockApplier) ApplyAddField(ctx context.Context, f dbschema.FieldDef, opts ddl.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyAddField", ctx, f, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyAddField indicates an expected call of ApplyAddField.
func (mr *MockApplierMockRecorder) ApplyAddField(ctx, f, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyAddField", reflect.TypeOf((*MockApplier)(nil).ApplyAddField), ctx, f, opts)
}

// ApplyAddIndex mocks base method.
func (m *MockApplier) ApplyAddIndex(ctx context.Context, idx dbschema.IndexDef, opts ddl.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyAddIndex", ctx, idx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyAddIndex indicates an expected call of ApplyAddIndex.
func (mr *MockApplierMockRecorder) ApplyAddIndex(ctx, idx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyAddIndex", reflect.TypeOf((*MockApplier)(nil).ApplyAddIndex), ctx, idx, opts)
}

// ApplyDropField mocks base method.
func (m *MockApplier) ApplyDropField(ctx context.Context, name dal.FieldName, opts ddl.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyDropField", ctx, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyDropField indicates an expected call of ApplyDropField.
func (mr *MockApplierMockRecorder) ApplyDropField(ctx, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyDropField", reflect.TypeOf((*MockApplier)(nil).ApplyDropField), ctx, name, opts)
}

// ApplyDropIndex mocks base method.
func (m *MockApplier) ApplyDropIndex(ctx context.Context, name string, opts ddl.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyDropIndex", ctx, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyDropIndex indicates an expected call of ApplyDropIndex.
func (mr *MockApplierMockRecorder) ApplyDropIndex(ctx, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyDropIndex", reflect.TypeOf((*MockApplier)(nil).ApplyDropIndex), ctx, name, opts)
}

// ApplyModifyField mocks base method.
func (m *MockApplier) ApplyModifyField(ctx context.Context, name dal.FieldName, newDef dbschema.FieldDef, opts ddl.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyModifyField", ctx, name, newDef, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyModifyField indicates an expected call of ApplyModifyField.
func (mr *MockApplierMockRecorder) ApplyModifyField(ctx, name, newDef, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyModifyField", reflect.TypeOf((*MockApplier)(nil).ApplyModifyField), ctx, name, newDef, opts)
}

// ApplyRenameField mocks base method.
func (m *MockApplier) ApplyRenameField(ctx context.Context, oldName, newName dal.FieldName, opts ddl.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyRenameField", ctx, oldName, newName, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyRenameField indicates an expected call of ApplyRenameField.
func (mr *MockApplierMockRecorder) ApplyRenameField(ctx, oldName, newName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRenameField", reflect.TypeOf((*MockApplier)(nil).ApplyRenameField), ctx, oldName, newName, opts)
}
