// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dal-go/dalgo/ddl (interfaces: SchemaModifier)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_ddl/schema_modifier.go github.com/dal-go/dalgo/ddl SchemaModifier
//

// Package mock_ddl is a generated GoMock package.
package mock_ddl

import (
	context "context"
	reflect "reflect"

	dbschema "github.com/dal-go/dalgo/dbschema"
	ddl "github.com/dal-go/dalgo/ddl"
	gomock "go.uber.org/mock/gomock"
)

// MockSchemaModifier is a mock of SchemaModifier interface.
type MockSchemaModifier struct {
	ctrl     *gomock.Controller
	recorder *MockSchemaModifierMockRecorder
	isgomock struct{}
}

// MockSchemaModifierMockRecorder is the mock recorder for MockSchemaModifier.
type MockSchemaModifierMockRecorder struct {
	mock *MockSchemaModifier
}

// NewMockSchemaModifier creates a new mock instance.
func NewMockSchemaModifier(ctrl *gomock.Controller) *MockSchemaModifier {
	mock := &MockSchemaModifier{ctrl: ctrl}
	mock.recorder = &MockSchemaModifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchemaModifier) EXPECT() *MockSchemaModifierMockRecorder {
	return m.recorder
}

// AlterCollection mocks base method.
func (m *MockSchemaModifier) AlterCollection(ctx context.Context, name string, ops ...ddl.AlterOp) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range ops {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AlterCollection", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AlterCollection indicates an expected call of AlterCollection.
func (mr *MockSchemaModifierMockRecorder) AlterCollection(ctx, name any, ops ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, ops...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlterCollection", reflect.TypeOf((*MockSchemaModifier)(nil).AlterCollection), varargs...)
}

// CreateCollection mocks base method.
func (m *MockSchemaModifier) CreateCollection(ctx context.Context, c dbschema.CollectionDef, opts ...ddl.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, c}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCollection", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCollection indicates an expected call of CreateCollection.
func (mr *MockSchemaModifierMockRecorder) CreateCollection(ctx, c any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, c}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollection", reflect.TypeOf((*MockSchemaModifier)(nil).CreateCollection), varargs...)
}

// DropCollection mocks base method.
func (m *MockSchemaModifier) DropCollection(ctx context.Context, name string, opts ...ddl.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DropCollection", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropCollection indicates an expected call of DropCollection.
func (mr *MockSchemaModifierMockRecorder) DropCollection(ctx, name any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropCollection", reflect.TypeOf((*MockSchemaModifier)(nil).DropCollection), varargs...)
}
