// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dal-go/dalgo/ddl (interfaces: TransactionalDDL)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_ddl/transactional.go github.com/dal-go/dalgo/ddl TransactionalDDL
//

// Package mock_ddl is a generated GoMock package.
package mock_ddl

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransactionalDDL is a mock of TransactionalDDL interface.
type MockTransactionalDDL struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionalDDLMockRecorder
	isgomock struct{}
}

// MockTransactionalDDLMockRecorder is the mock recorder for MockTransactionalDDL.
type MockTransactionalDDLMockRecorder struct {
	mock *MockTransactionalDDL
}

// NewMockTransactionalDDL creates a new mock instance.
func NewMockTransactionalDDL(ctrl *gomock.Controller) *MockTransactionalDDL {
	mock := &MockTransactionalDDL{ctrl: ctrl}
	mock.recorder = &MockTransactionalDDLMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionalDDL) EXPECT() *MockTransactionalDDLMockRecorder {
	return m.recorder
}

// SupportsTransactionalDDL mocks base method.
func (m *MockTransactionalDDL) SupportsTransactionalDDL() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsTransactionalDDL")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsTransactionalDDL indicates an expected call of SupportsTransactionalDDL.
func (mr *MockTransactionalDDLMockRecorder) SupportsTransactionalDDL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsTransactionalDDL", reflect.TypeOf((*MockTransactionalDDL)(nil).SupportsTransactionalDDL))
}
