// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dal-go/dalgo/dal (interfaces: RecordsetReader)
//
// Generated by this command:
//
//	mockgen github.com/dal-go/dalgo/dal RecordsetReader
//

// Package mock_dal is a generated GoMock package.
package mock_dal

import (
	reflect "reflect"

	recordset "github.com/dal-go/dalgo/recordset"
	gomock "go.uber.org/mock/gomock"
)

// MockRecordsetReader is a mock of RecordsetReader interface.
type MockRecordsetReader struct {
	ctrl     *gomock.Controller
	recorder *MockRecordsetReaderMockRecorder
	isgomock struct{}
}

// MockRecordsetReaderMockRecorder is the mock recorder for MockRecordsetReader.
type MockRecordsetReaderMockRecorder struct {
	mock *MockRecordsetReader
}

// NewMockRecordsetReader creates a new mock instance.
func NewMockRecordsetReader(ctrl *gomock.Controller) *MockRecordsetReader {
	mock := &MockRecordsetReader{ctrl: ctrl}
	mock.recorder = &MockRecordsetReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordsetReader) EXPECT() *MockRecordsetReaderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRecordsetReader) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRecordsetReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRecordsetReader)(nil).Close))
}

// Cursor mocks base method.
func (m *MockRecordsetReader) Cursor() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cursor")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cursor indicates an expected call of Cursor.
func (mr *MockRecordsetReaderMockRecorder) Cursor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cursor", reflect.TypeOf((*MockRecordsetReader)(nil).Cursor))
}

// Next mocks base method.
func (m *MockRecordsetReader) Next() (recordset.Row, recordset.Recordset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(recordset.Row)
	ret1, _ := ret[1].(recordset.Recordset)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Next indicates an expected call of Next.
func (mr *MockRecordsetReaderMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockRecordsetReader)(nil).Next))
}

// Recordset mocks base method.
func (m *MockRecordsetReader) Recordset() recordset.Recordset {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recordset")
	ret0, _ := ret[0].(recordset.Recordset)
	return ret0
}

// Recordset indicates an expected call of Recordset.
func (mr *MockRecordsetReaderMockRecorder) Recordset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recordset", reflect.TypeOf((*MockRecordsetReader)(nil).Recordset))
}
