// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dal-go/dalgo/dal (interfaces: RecordsReader)
//
// Generated by this command:
//
//	mockgen github.com/dal-go/dalgo/dal RecordsReader
//

// Package mock_dal is a generated GoMock package.
package mock_dal

import (
	reflect "reflect"

	dal "github.com/dal-go/dalgo/dal"
	gomock "go.uber.org/mock/gomock"
)

// MockRecordsReader is a mock of RecordsReader interface.
type MockRecordsReader struct {
	ctrl     *gomock.Controller
	recorder *MockRecordsReaderMockRecorder
	isgomock struct{}
}

// MockRecordsReaderMockRecorder is the mock recorder for MockRecordsReader.
type MockRecordsReaderMockRecorder struct {
	mock *MockRecordsReader
}

// NewMockRecordsReader creates a new mock instance.
func NewMockRecordsReader(ctrl *gomock.Controller) *MockRecordsReader {
	mock := &MockRecordsReader{ctrl: ctrl}
	mock.recorder = &MockRecordsReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordsReader) EXPECT() *MockRecordsReaderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRecordsReader) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRecordsReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRecordsReader)(nil).Close))
}

// Cursor mocks base method.
func (m *MockRecordsReader) Cursor() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cursor")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cursor indicates an expected call of Cursor.
func (mr *MockRecordsReaderMockRecorder) Cursor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cursor", reflect.TypeOf((*MockRecordsReader)(nil).Cursor))
}

// Next mocks base method.
func (m *MockRecordsReader) Next() (dal.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(dal.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockRecordsReaderMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockRecordsReader)(nil).Next))
}
