name: Go CI

on:
  push:
    branches-ignore:
      - renovate/**
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to matching v*, i.e. v20.15.10
  pull_request:
    branches:
      - '**'

jobs:

  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@d7e8306011d4b0aa51d311a2f1e2a50b7cd9d7d0

    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      code_coverage: true
