name: Go CI

on:
  push:
    branches-ignore:
      - renovate/**
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to matching v*, i.e. v20.15.10
  pull_request:
    branches:
      - '**'

jobs:

  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@e74cc25456ec532599871b1d84fd1d3fca90e563

    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    with:
      code_coverage: true
